//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yerpe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Text { get; set; }
        public int RoomId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
